steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '-t', 'script-runner', '.']
- name: 'script-runner'
  args: ["sh"]
images: ['gcr.io/$PROJECT_ID/custom-script-test2']  