steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://irish-gen-build-dependencies/apache-jena-3.14.0.tar.gz', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/irish-gen-build', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', 'gcr.io/$PROJECT_ID/irish-gen-build', 'bash']
    env: ['IRISH_GEN_HOME=/workspace']

images:
  - 'gcr.io/$PROJECT_ID/irish-gen-build'
