steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '-f', 'Dockerfile', '-t', 'script-runner' ,'.']
- name: 'script-runner'
  args: ["sh", "build.sh"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/custom-script-test2', '.']  
images: ['gcr.io/$PROJECT_ID/custom-script-test2']