steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/irish-gen-build:apache-jena-4-1']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--volume', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/irish-gen-build:apache-jena-4-1', 'bash']
