steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/$PROJECT_ID/script-runner', '.']
- name: 'script-runner'
  args: ["sh", "./build.sh"]
images: ['gcr.io/$PROJECT_ID/script-runner']