steps:
  - name: 'Docker Pull'
    args: ['pull', 'us-docker.pkg.dev/$PROJECT_ID/irish-gen-builds-docker/apache-jena:apache-jena-4-3-2']
  - name: 'Docker Run'
    args: ['run', '--volume', '/workspace:/workspace', 'us-docker.pkg.dev/$PROJECT_ID/irish-gen-builds-docker/apache-jena:apache-jena-4-3-2', 'bash']
