steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/script-runner', '.']
- name: 'ubuntu'
  args: ["bash", "./build.sh"]
images: ['gcr.io/$PROJECT_ID/script-runner']